{{- if and (eq .Values.kind "CronJob") .Values.containers }}
{{- $commonLabels := include "helm-base.commonLabels" . }}
{{- $annotations := include "helm-base.commonAnnotations" . }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "helm-base.fullname" . }}
  labels:
{{ $commonLabels | nindent 4 }}
  annotations:
{{ $annotations | nindent 4 }}
spec:
  {{- if .Values.concurrencyPolicy }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  {{- end }}
  schedule: {{ required "A valid .Values.schedule entry required!" .Values.schedule | quote }}
  {{- if .Values.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  {{- end }}
  suspend: {{ default .Values.suspend false }}

  jobTemplate:
    spec:
      {{- if .Values.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds }}
      {{- end }}
      {{- if .Values.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: {{ .Values.backoffLimit }}
      template:
        {{- include "helm-base.pod" . | nindent 8 }}
{{- end }}