{{- if and (.Values.containers) (eq .Values.kind "DaemonSet") }}

{{- $selectorLabels := include "helm-base.selectorLabels" . }}
{{- $commonLabels := include "helm-base.commonLabels" . }}
{{- $commonAnnotations := include "helm-base.commonAnnotations" . }}

apiVersion: {{ .Values.apiVersion }}
kind: {{ .Values.kind }}
metadata:
  name: {{ template "helm-base.fullname" . }}
  labels:
{{ $selectorLabels | indent 4 }}
  annotations:
{{- $commonAnnotations | nindent 4 }}
spec:
  {{- if $.Values.minReadySeconds }}
  minReadySeconds: {{ $.Values.minReadySeconds }}
  {{- end }}
  revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ $selectorLabels | indent 6 }}
  template:
    {{- include "helm-base.pod" . }}

{{- end }}


