{{- if and (.Values.containers) (eq .Values.kind "DaemonSet") }}

{{- $selectorLabels := include "helm-base.selectorLabels" . }}
{{- $commonLabels := include "helm-base.commonLabels" . }}
{{- $volumes := include "helm-base.volumes" . }}
{{- $commonAnnotations := include "helm-base.commonAnnotations" . }}
{{- $podAnnotations := include "helm-base.podAnnotations" . }}

apiVersion: {{ .Values.apiVersion }}
kind: {{ .Values.kind }}
metadata:
  name: {{ template "helm-base.fullname" . }}
  labels:
{{ $selectorLabels | indent 4 }}
spec:
  {{- if $.Values.minReadySeconds }}
  minReadySeconds: {{ $.Values.minReadySeconds }}
  {{- end }}
  revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ $selectorLabels | indent 6 }}
  template:
    {{- include "helm-base.pod" . }}

{{ $volumes | indent 6 }}

{{- end }}
