{{- if and (.Values.containers) (eq .Values.kind "Deployment") }}

{{- $selectorLabels := include "helm-base.selectorLabels" . }}
{{- $podLabels := include "helm-base.podLabels" . }}
{{- $commonAnnotations := include "helm-base.commonAnnotations" . }}
{{- $podAnnotations := include "helm-base.podAnnotations" . }}

apiVersion: {{ .Values.apiVersion }}
kind: Deployment 
metadata:
  name: {{ template "helm-base.fullname" . }}
  labels:
{{- $selectorLabels | nindent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  progressDeadlineSeconds: {{ $.Values.progressDeadlineSeconds }}
  {{- if $.Values.minReadySeconds }}
  minReadySeconds: {{ $.Values.minReadySeconds }}
  {{- end }}
  revisionHistoryLimit: {{ $.Values.revisionHistoryLimit }}
  strategy:
    type: {{ $.Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ $.Values.strategy.maxUnavailable }}
      {{- if $.Values.strategy.maxSurge }}
      maxSurge: {{ $.Values.strategy.maxSurge }}
      {{- end }}
  selector:
    matchLabels:
{{ $selectorLabels | indent 6 }}
  template:
    {{- include "helm-base.pod" . }}


{{- end }}
