{{- $commonLabels := include "helm-base.commonLabels" . }}
{{- $commonAnnotations := include "helm-base.commonAnnotations" . }}
{{- $name := include "helm-base.fullname" . }}
{{- $root := $ }}

{{- range $k, $h := .Values.hooks }}
{{ $kind := default "Job" $h.kind }}

{{- if eq $kind "Job" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}-{{ $h.name }}
  labels:
{{ $commonLabels | indent 4 }}
  annotations:
    "helm.sh/hook": {{ default "pre-upgrade,pre-install" (tpl $h.onEvent $root) }}
    "helm.sh/hook-weight": "{{ default (mul -1 (add1 $k)) $h.weight}}"
    "helm.sh/hook-delete-policy": {{ default "before-hook-creation" $h.deletePolicy }}
spec:
  template:
    metadata:
      labels:
{{ $commonLabels | indent 8 }}
      name: {{ $name }}
      annotations:
    {{- if $h.annotations }}
      {{- range $k, $v := $h.annotations }}
        {{ $k }}: "{{ tpl $v $ }}"
      {{- end }}
    {{- end }}
{{ $commonAnnotations | indent 8 }}
    spec:
      {{- if $h.serviceAccount }}
      serviceAccount: {{ tpl $h.serviceAccount.name $ }}
      {{- end}}
      restartPolicy: {{ default "Never" $h.restartPolicy }}
      {{- if $.Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range $_, $s := $.Values.imagePullSecrets }}
      - name: "{{ $s }}"
      {{- end }}
      {{- end }}

{{- if $h.initContainers }}
      initContainers:
{{- range $k, $c := $h.initContainers }}
{{- $new := dict }}
{{- range $k, $v := $ }}
{{- $_ := set $new $k $v }}
{{- end }}
{{- range $k, $v := $c }}
{{- $_ := set $new $k $v }}
{{- end }}
{{ include "helm-base.containerBase" $new | indent 6 }}
{{- end }}
{{- end }}

      containers:
{{- $hvols := dict }}
{{- range $k, $c := $h.containers }}
{{- $new := dict }}
{{- range $k, $v := $ }}
{{- $_ := set $new $k $v }}
{{- end }}
{{- range $k, $v := $c }}
{{- $_ := set $new $k $v }}
{{- end }}
{{ include "helm-base.containerBase" $new | indent 6 }}
{{ $hvols = $new }}
{{- end }}

  {{- if $.Values.nodeSelector }}
    {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
  {{- if $.Values.affinity }}
    {{- with $.Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
    {{- end }}
  {{- end }}
  {{- if $.Values.tolerations }}
    {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- end }}

{{- $n2 := dict }}
{{- $_ := set $n2 "volumes" $h.volumes }}
{{- $_ := set $n2 "Values" $.Values }}
{{- $_ := set $n2 "Chart" $.Chart }}
{{- $_ := set $n2 "Release" $.Release }}
{{- $_ := set $n2 "Template" $.Template }}
{{- $volumes := include "helm-base.hookvolumes" $n2 }}
{{- $volumes | indent 6 }}

{{- end }} {{/* End Job kind*/}}


{{- if eq $kind "ConfigMap" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-{{ $h.name }}
  labels:
{{ $commonLabels | indent 4 }}
  annotations:
    "helm.sh/hook": {{ default "pre-upgrade,pre-install" $h.onEvent }}
    "helm.sh/hook-weight": "{{ default (mul -1 (add1 $k)) $h.weight}}"
data:
{{- if eq (kindOf $h.data) "map" }}
  {{- range $k, $d := $h.data}}
  {{- if gt (len (splitList "\n" $d)) 1 }}
  {{ tpl $k $ }}: |-
{{ (tpl $d $) | indent 4 }}
  {{- else }}
  {{ tpl $k $ }}: {{ tpl (tpl $d $) $ }}
  {{- end }} {{/* end if multiline */}}
  {{- end }} {{/* end range */}}

{{- else if eq (kindOf $h.data) "string" }}
  {{- tpl $h.name $ }}: |
{{ (tpl $h.data $) | indent 4 }}
{{- else }}
  DATATYPE: {{ kindOf $h.data }}
{{- end }} {{/* end if type */}}
{{- end }} {{/* End ConfigMap kind */}}



{{- if and ($h.rbac) ($h.serviceAccount) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  labels:
{{- $commonLabels | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ default "pre-upgrade,pre-install" $h.onEvent }}
    "helm.sh/hook-weight": "{{ default (mul -1 (add1 $k)) $h.weight}}"
rules:
{{ toYaml $h.rbac.rules }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $name }}
  labels:
{{- $commonLabels | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ default "pre-upgrade,pre-install" $h.onEvent }}
    "helm.sh/hook-weight": "{{ default (mul -1 (add1 $k)) $h.weight}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $name }}
subjects:
- kind: ServiceAccount
  name: {{ tpl $h.serviceAccount.name $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}


{{- if $h.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl $h.serviceAccount.name $ }}
  annotations:
    "helm.sh/hook": {{ default "pre-upgrade,pre-install" $h.onEvent }}
    "helm.sh/hook-weight": "{{ default (mul -1 (add1 $k)) $h.weight}}"
{{- if $h.serviceAccount.annotations }}
{{ toYaml $h.serviceAccount.annotations | indent 4 }}
{{ end }}
  labels:
{{ $commonLabels | indent 4 }}
{{ end }}




{{- end }}
