{{- if and (.Values.containers) (eq .Values.kind "Job") }}

{{- $selectorLabels := include "helm-base.selectorLabels" . }}
{{- $podLabels := include "helm-base.podLabels" . }}
{{- $volumes := include "helm-base.volumes" . }}
{{- $commonAnnotations := include "helm-base.commonAnnotations" . }}
{{- $podAnnotations := include "helm-base.podAnnotations" . }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "helm-base.fullname" . }}
  labels:
{{- $selectorLabels | nindent 4 }}
spec:
  backoffLimit: {{ $.Values.backoffLimit | default 3 }}
  activeDeadlineSeconds: {{ $.Values.activeDeadlineSeconds | default 1800 }}
  template:
    {{- include "helm-base.pod" . }}

{{ $volumes | indent 6 }}

{{- end }}
