{{- if and (.Values.containers) (eq .Values.kind "Job") }}

{{- $selectorLabels := include "helm-base.selectorLabels" . }}
{{- $commonAnnotations := include "helm-base.commonAnnotations" . }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "helm-base.fullname" . }}
  labels:
{{- $selectorLabels | nindent 4 }}
  annotations:
{{- $commonAnnotations | nindent 4 }}
spec:
  backoffLimit: {{ $.Values.backoffLimit | default 3 }}
  activeDeadlineSeconds: {{ $.Values.activeDeadlineSeconds | default 1800 }}
  template:
    {{- include "helm-base.pod" . }}

{{- end }}
