{{- $root := $ -}}
{{- $name := include "helm-base.fullname" . }}
{{- $commonLabels := include "helm-base.commonLabels" . }}
{{- $commonAnnotations := include "helm-base.commonAnnotations" . }}

{{- if and ($root.Values.secretStore.name) ($root.Values.externalSecrets) ($root.Values.secretStore.create) }}
{{- $name := default (printf "%s-%s" $name $root.Values.secretStore.name) $root.Values.secretStore.fullname }}
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ $name }}
  labels:
{{- $commonLabels | nindent 4 }}
  {{- if $commonAnnotations }}
  annotations:
{{- $commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  provider:
    aws:
      service: {{ $root.Values.secretStore.service }}
      region: {{ $root.Values.secretStore.region }}
{{- end }}