{{ if .Values.serviceAccount.create }}
{{- $commonLabels := include "helm-base.commonLabels" . }}
{{- $name := include "helm-base.serviceAccountName" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{ end }}
  labels:
{{ $commonLabels | indent 4 }}
{{ end }}
