{{ $fullname := include "infra-labels.fullname" . }}
{{ $labels := include "infra-labels.labels" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}
  labels:
    {{- $labels | nindent 4 }}
data:
{{- range $key, $val := .Values.labels }}
  {{ $key }}: {{ $val }}
{{- end }}